#=============================================================================
# Filename: init.toml 
# Place init.toml at ~/.SpaceVim.d/
#=============================================================================

# All SpaceVim option below [option] section
[options]
    automatic_update = true
    colorscheme = "molokai" # by default, colorscheme layer is not loaded, if you want to use more colorscheme, please load the colorscheme layer
    colorscheme_bg = "dark"
    enable_guicolors = true # Disable guicolors in basic mode, many terminal do not support 24bit true colors
    statusline_separator = "arrow" # Disable statusline separator, if you want to use other value, please install nerd fonts
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    filetree_direction = 'left'
    enable_vimfiler_gitstatus = true
    enable_cursorline = false
    filetype_icon = true
    enable_tabline_filetype_icon = true
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "smart"

[[layers]]
  name = "lsp"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = "japanese"

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "ui"
  enable = true
  enable_sidebar = true

[[layers]]
  name = "git"

[[layers]]
  name = "github"

[[layers]]
  name = "fzf"

[[layers]]
  name = "tools"

[[layers]]
  name = "lang#dockerfile"

# [[layers]]
#   name = "lang#go"

[[layers]]
  name = "lang#html"

[[layers]]
  name = "lang#javascript"
  auto_fix = true
  enable_flow_syntax = true

[[layers]]
  name = "lang#vue"

[[layers]]
  name = "lang#sh"
